#pragma once
// Must be included AFTER <lvgl.h> so LV_FONT_DECLARE is defined.
// Declares custom Montserrat fonts with extended Latin (Ä Ö Ü ä ö ü ß).
// Generated by tools/generate_fonts.sh — do not edit manually.

#include "lv_conf.h"

#if BRL_USE_EXTENDED_FONTS
  LV_FONT_DECLARE(brl_font_montserrat_14)
  LV_FONT_DECLARE(brl_font_montserrat_16)
  LV_FONT_DECLARE(brl_font_montserrat_20)
  LV_FONT_DECLARE(brl_font_montserrat_24)
  LV_FONT_DECLARE(brl_font_montserrat_32)
  LV_FONT_DECLARE(brl_font_montserrat_40)
  LV_FONT_DECLARE(brl_font_montserrat_48)
#endif
