/**
 * @file lv_conf.h
 * LVGL 9 configuration for BRL Laptimer
 * Waveshare ESP32-S3 7-Inch LCD (800x480, RGB565)
 */

#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

/*====================
   COLOR SETTINGS
 *====================*/

/* Color depth: 16 (RGB565) */
#define LV_COLOR_DEPTH 16

/*=========================
   STDLIB WRAPPER SETTINGS
 *=========================*/

/* Use C stdlib malloc/free — on ESP32 with PSRAM this uses all available RAM */
#define LV_USE_STDLIB_MALLOC    LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING    LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF   LV_STDLIB_CLIB

/*====================
   HAL SETTINGS
 *====================*/

/* Default display refresh period in ms */
#define LV_DEF_REFR_PERIOD  10

/* Input device read period in ms */
#define LV_INDEV_DEF_READ_PERIOD 30

/* Align draw buffer to this many bytes */
#define LV_DRAW_BUF_ALIGN   4


/*=====================
   RENDERING SETTINGS
 *=====================*/

/* Default draw context (software) */
#define LV_USE_DRAW_SW 1

/* Enable 16-bit color swap for flush */
#define LV_DRAW_SW_COMPLEX 1

/* Disable ARM-specific ASM optimisations (Helium/NEON) — ESP32-S3 uses Xtensa */
#define LV_DRAW_SW_ASM LV_DRAW_SW_ASM_NONE

/*=======================
   FEATURE CONFIGURATION
 *=======================*/

/* Large memory - enable all font/widget features */
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_MONTSERRAT_40 1
#define LV_FONT_MONTSERRAT_48 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14

/*
 * Extended Latin fonts (Ä Ö Ü ä ö ü ß etc.)
 *
 * LVGL's built-in Montserrat only covers ASCII (0x20–0x7E).
 * To get German umlauts:
 *   1. Run:  tools/generate_fonts.sh   (requires Node + lv_font_conv + Montserrat-Regular.ttf)
 *   2. Set:  BRL_USE_EXTENDED_FONTS  1   (below)
 *
 * Once enabled, brl_font_NN aliases replace lv_font_montserrat_NN everywhere in the UI.
 * All font sizes (14 16 20 24 32 40 48) are covered.
 */
#define BRL_USE_EXTENDED_FONTS  0   /* change to 1 after running generate_fonts.sh */

#if BRL_USE_EXTENDED_FONTS
  /* Custom fonts generated by tools/generate_fonts.sh */
  LV_FONT_DECLARE(brl_font_montserrat_14)
  LV_FONT_DECLARE(brl_font_montserrat_16)
  LV_FONT_DECLARE(brl_font_montserrat_20)
  LV_FONT_DECLARE(brl_font_montserrat_24)
  LV_FONT_DECLARE(brl_font_montserrat_32)
  LV_FONT_DECLARE(brl_font_montserrat_40)
  LV_FONT_DECLARE(brl_font_montserrat_48)
  /* Alias macros so all UI code uses the same name */
  #define BRL_FONT_14  brl_font_montserrat_14
  #define BRL_FONT_16  brl_font_montserrat_16
  #define BRL_FONT_20  brl_font_montserrat_20
  #define BRL_FONT_24  brl_font_montserrat_24
  #define BRL_FONT_32  brl_font_montserrat_32
  #define BRL_FONT_40  brl_font_montserrat_40
  #define BRL_FONT_48  brl_font_montserrat_48
#else
  /* Fall back to built-in ASCII-only Montserrat */
  #define BRL_FONT_14  lv_font_montserrat_14
  #define BRL_FONT_16  lv_font_montserrat_16
  #define BRL_FONT_20  lv_font_montserrat_20
  #define BRL_FONT_24  lv_font_montserrat_24
  #define BRL_FONT_32  lv_font_montserrat_32
  #define BRL_FONT_40  lv_font_montserrat_40
  #define BRL_FONT_48  lv_font_montserrat_48
#endif

/* Enable extra drawing capabilities */
#define LV_USE_ARC        1
#define LV_USE_BAR        1
#define LV_USE_BTN        1
#define LV_USE_BTNMATRIX  1
#define LV_USE_CANVAS     1
#define LV_USE_CHECKBOX   1
#define LV_USE_DROPDOWN   1
#define LV_USE_IMG        1
#define LV_USE_LABEL      1
#define LV_USE_LINE       1
#define LV_USE_ROLLER     1
#define LV_USE_SLIDER     1
#define LV_USE_SWITCH     1
#define LV_USE_TEXTAREA   1
#define LV_USE_TABLE      1
#define LV_USE_CHART      1
#define LV_USE_LED        1
#define LV_USE_MSGBOX     1
#define LV_USE_SPINBOX    1
#define LV_USE_SPINNER    1
#define LV_USE_TABVIEW    1
#define LV_USE_TILEVIEW   1
#define LV_USE_WIN        1
#define LV_USE_SPAN       1
#define LV_USE_METER      1

/* Animation */
#define LV_USE_ANIM 1

/* Image decoders */
#define LV_USE_BMP   0
#define LV_USE_GIF   0
#define LV_USE_PNG   0
/* JPEG via TJpgDec — lightweight, fits well on ESP32 */
#define LV_USE_TJPGD 1

/* Logging */
#define LV_USE_LOG 0

/* Use assert */
#define LV_USE_ASSERT_NULL          1
#define LV_USE_ASSERT_MALLOC        1
#define LV_USE_ASSERT_STYLE         0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ           0

/*===================
   DEMO USAGE
 *===================*/

/* Enable demo widgets for testing */
#define LV_USE_DEMO_WIDGETS 1
#define LV_USE_DEMO_BENCHMARK 0
#define LV_USE_DEMO_STRESS 0
#define LV_USE_DEMO_MUSIC 0

/*==================
 * EXAMPLES
 *==================*/
#define LV_BUILD_EXAMPLES 0

/*===================
 * PERF MONITOR
 *==================*/
#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR  0

#endif /* LV_CONF_H */
