#pragma once
// Declares custom Montserrat fonts with extended Latin (Ae Oe Ue ae oe ue ss).
// Generated by tools/generate_fonts.sh -- do not edit manually.

#include <lvgl.h>

LV_FONT_DECLARE(brl_font_montserrat_14)
LV_FONT_DECLARE(brl_font_montserrat_16)
LV_FONT_DECLARE(brl_font_montserrat_20)
LV_FONT_DECLARE(brl_font_montserrat_24)
LV_FONT_DECLARE(brl_font_montserrat_32)
LV_FONT_DECLARE(brl_font_montserrat_40)
LV_FONT_DECLARE(brl_font_montserrat_48)
LV_FONT_DECLARE(brl_font_montserrat_64)

// Convenience macros (previously in lv_conf.h, now needed explicitly)
#define BRL_FONT_14  brl_font_montserrat_14
#define BRL_FONT_16  brl_font_montserrat_16
#define BRL_FONT_20  brl_font_montserrat_20
#define BRL_FONT_24  brl_font_montserrat_24
#define BRL_FONT_32  brl_font_montserrat_32
#define BRL_FONT_40  brl_font_montserrat_40
#define BRL_FONT_48  brl_font_montserrat_48
#define BRL_FONT_64  brl_font_montserrat_64
